### PR TITLE
Hello React and Rails: 2 different repositories (Frontend)

### PR DESCRIPTION
**Pull request by eroiyo**
Hello Microverse Community!

In this project we have tested the 2 repository project approach, having the backend in an repository, and the front end in other is comfortable to use and is easier to find information to maintain 2 different technology separated than together, overall is a good methodology

Thanks for reading

The link to the backend pull request is [here](https://github.com/eroiyo/hello-rails-back-end/pull/1)

### CODE REVIEW

**Review by henatan99 — COMMENTED** [review]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, whose back-end rails app does not have a pull request. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by eroiyo** [comment]
Thanks for the reply, i will add it a pull request

**Comment by eroiyo** [comment]
Added the pull request of the backend project, can access clicking [here](https://github.com/eroiyo/hello-rails-back-end/pull/1)

**Review by sinansevgi — APPROVED** [review]
# Approved :heavy_check_mark: 

Hi @eroiyo , 

Great Work!
Both react app and rails app work well :clap:
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by eroiyo** [comment]
Thanks for the review! i will merget it

**Pull request merged**
